/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "S21_Math_tests.check" instead.
 */

#include <check.h>

#line 1 "s21_Math_tests.check"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "s21_Math.h"

//! s21_abs

START_TEST(s21_abs_test_1)
{
#line 9
ck_assert_double_eq(abs(-10), s21_abs(-10));

}
END_TEST

START_TEST(s21_abs_test_2)
{
#line 12
ck_assert_double_eq(abs(7895), s21_abs(7895));

}
END_TEST

START_TEST(s21_abs_test_3)
{
#line 15
ck_assert_double_eq(abs(-10101), s21_abs(-10101));

}
END_TEST

START_TEST(s21_abs_test_4)
{
#line 18
ck_assert_double_eq(abs(10101), s21_abs(10101));

}
END_TEST

START_TEST(s21_abs_test_5)
{
#line 21
for (int i = -128; i <= 127; i++) {
    ck_assert_int_eq(abs(i), s21_abs(i));
}

//! s21_acos tests

}
END_TEST

START_TEST(s21_acos_test_1)
{
#line 28
ck_assert_double_eq(acos(0), s21_acos(0));

}
END_TEST

START_TEST(s21_acos_test_2)
{
#line 31
for (double i = -1.000000; i <= 1; i += 0.00005)
    ck_assert_double_eq_tol(acos(i), s21_acos(i), 1e-6);

}
END_TEST

START_TEST(s21_acos_test_3)
{
#line 35
ck_assert_double_nan(s21_acos(-S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_acos_test_4)
{
#line 38
for (double i = -1.000000; i <= 1.000000; i += 0.00003)
    ck_assert_double_eq_tol(acos(i), s21_acos(i), 1e-6);

}
END_TEST

START_TEST(s21_acos_test_5)
{
#line 42
for (double i = -1.000000; i <= 1.000000; i += 0.00001)
    ck_assert_double_eq_tol(acos(i), s21_acos(i), 1e-6);

}
END_TEST

START_TEST(s21_acos_test_6)
{
#line 46
ck_assert_double_nan(s21_acos(S21_NAN_VAL));

}
END_TEST

START_TEST(s21_acos_test_7)
{
#line 49
ck_assert_double_nan(s21_acos(-1.0/0.0));

}
END_TEST

START_TEST(s21_acos_test_8)
{
#line 52
ck_assert_double_nan(s21_acos(6.654));

}
END_TEST

START_TEST(s21_acos_test_9)
{
#line 55
ck_assert_double_nan(s21_acos(1.5 * S21_M_PI));

}
END_TEST

START_TEST(s21_acos_test_10)
{
#line 58
ck_assert_double_eq_tol(acos(0.00001), s21_acos(0.00001), 1e-6);

//! s21_asin tests

}
END_TEST

START_TEST(s21_asin_test_1)
{
#line 63
for (double i = -1.000000; i <= 1.000000; i += 0.00005)
    ck_assert_double_eq_tol(asin(i), s21_asin(i), 1e-6);
    
}
END_TEST

START_TEST(s21_asin_test_2)
{
#line 67
for (double i = -1.000000; i <= 1.000000; i += 0.00001)
    ck_assert_double_eq_tol(asin(i), s21_asin(i), 1e-6);

}
END_TEST

START_TEST(s21_asin_test_3)
{
#line 71
ck_assert_double_nan(s21_asin(S21_NAN_VAL));
    
}
END_TEST

START_TEST(s21_asin_test_4)
{
#line 74
ck_assert_double_eq_tol(asin(1), s21_asin(1), 1e-7);

}
END_TEST

START_TEST(s21_asin_test_5)
{
#line 77
ck_assert_double_eq_tol(asin(-1), s21_asin(-1), 1e-6);

}
END_TEST

START_TEST(s21_asin_test_6)
{
#line 80
for (double i = -1.000000; i <= 1.000000; i += 0.00003)
    ck_assert_double_eq_tol(asin(i), s21_asin(i), 1e-6);

}
END_TEST

START_TEST(s21_asin_test_7)
{
#line 84
ck_assert_double_eq_tol(asin(0), s21_asin(0), 1e-6);

}
END_TEST

START_TEST(s21_asin_test_8)
{
#line 87
ck_assert_double_nan(s21_asin(INFINITY));

}
END_TEST

START_TEST(s21_asin_test_9)
{
#line 90
ck_assert_double_nan(s21_asin(-1.0/0.0));

}
END_TEST

START_TEST(s21_asin_test_10)
{
#line 93
ck_assert_double_nan(s21_asin(-252.568));

//! s21_atan tests

}
END_TEST

START_TEST(s21_atan_test_1)
{
#line 98
ck_assert_double_eq_tol(atan(500.000), s21_atan(500.000), 1e-4);

}
END_TEST

START_TEST(s21_atan_test_2)
{
#line 101
for (double i = -565.324; i <= 789.532; i += 50.6235)
    ck_assert_double_eq_tol(atan(i), s21_atan(i), 1e-6);

}
END_TEST

START_TEST(s21_atan_test_3)
{
#line 105
for (double i = -1.000000; i <= 1.000000; i += 0.00001)
    ck_assert_double_eq_tol(atan(i), s21_atan(i), 1e-7);

}
END_TEST

START_TEST(s21_atan_test_4)
{
#line 109
ck_assert_double_eq_tol(atan(-1.0/0.0), s21_atan(-1.0/0.0), 1e-7);

}
END_TEST

START_TEST(s21_atan_test_5)
{
#line 112
ck_assert_double_eq_tol(atan(0.0), s21_atan(0.0), 1e-7);

}
END_TEST

START_TEST(s21_atan_test_6)
{
#line 115
ck_assert_double_nan(s21_atan(0.0/0.0));

}
END_TEST

START_TEST(s21_atan_test_7)
{
#line 118
ck_assert_double_eq_tol(atan(0.0), s21_atan(0.0), 1e-7);

}
END_TEST

START_TEST(s21_atan_test_8)
{
#line 121
for (double i = -123456.789456; i <= 123456.789456; i += 1.0)
    ck_assert_double_eq_tol(atan(i), s21_atan(i), 1e-7);

}
END_TEST

START_TEST(s21_atan_test_9)
{
#line 125
ck_assert_double_eq_tol(atan(INFINITY), s21_atan(S21_HUGE_VAL), 1e-7);

}
END_TEST

START_TEST(s21_atan_test_10)
{
#line 128
ck_assert_double_eq_tol(atan(-2.78965), s21_atan(-2.78965), 1e-7);

//! s21_ceil tests

}
END_TEST

START_TEST(s21_ceil_test_1)
{
#line 133
double i;
for (i = -M_PI/2; i <= M_PI/2; i+= 0.25) {
    ck_assert_double_eq(ceil(i), s21_ceil(i));
}
}
END_TEST

START_TEST(s21_ceil_test_2)
{
#line 138
ck_assert_double_eq(ceil(INFINITY), s21_ceil(S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_ceil_test_3)
{
#line 141
ck_assert_double_eq(ceil(-INFINITY), s21_ceil(-S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_ceil_test_4)
{
#line 144
ck_assert_double_nan(ceil(NAN));

}
END_TEST

START_TEST(s21_ceil_test_5)
{
#line 147
ck_assert_double_nan(s21_ceil(S21_NAN_VAL));

}
END_TEST

START_TEST(s21_ceil_test_6)
{
#line 150
ck_assert_double_eq(ceil(-7.0), s21_ceil(-7.0));

}
END_TEST

START_TEST(s21_ceil_test_7)
{
#line 153
ck_assert_double_eq(ceil(-98.1), s21_ceil(-98.1));

}
END_TEST

START_TEST(s21_ceil_test_8)
{
#line 156
ck_assert_double_eq(ceil(123.02), s21_ceil(123.02));

}
END_TEST

START_TEST(s21_ceil_test_9)
{
#line 159
ck_assert_double_eq(ceil(10009.00123), s21_ceil(10009.00123));

}
END_TEST

START_TEST(s21_ceil_test_10)
{
#line 162
ck_assert_double_eq(ceil(-10009.555), s21_ceil(-10009.555));

}
END_TEST

START_TEST(s21_ceil_test_11)
{
#line 165
ck_assert_double_eq(ceil(-0.10009), s21_ceil(-0.10009));

}
END_TEST

START_TEST(s21_ceil_test_12)
{
#line 168
ck_assert_double_eq(ceil(-1e-23), s21_ceil(-1e-23));

}
END_TEST

START_TEST(s21_ceil_test_13)
{
#line 171
ck_assert_double_eq(ceil(7), s21_ceil(7));

}
END_TEST

START_TEST(s21_ceil_test_14)
{
#line 174
ck_assert_double_eq(ceil(0), s21_ceil(0));

}
END_TEST

START_TEST(s21_ceil_test_15)
{
#line 177
ck_assert_double_eq(ceil(0.0), s21_ceil(0.0));

//! s21_cos tests
}
END_TEST

START_TEST(s21_cos_test_1)
{
#line 181
for (double i = -1.000000; i <= 1.000000; i += 0.00001)
    ck_assert_double_eq_tol(cos(i), s21_cos(i), EPS);

}
END_TEST

START_TEST(s21_cos_test_2)
{
#line 185
ck_assert_double_nan(s21_cos(S21_NAN_VAL));

}
END_TEST

START_TEST(s21_cos_test_3)
{
#line 188
ck_assert_double_nan(s21_cos(-S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_cos_test_4)
{
#line 191
ck_assert_double_nan(s21_cos(S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_cos_test_5)
{
#line 194
for (double i = -223.654; i <= 148.522; i += 2.456)
    ck_assert_double_eq_tol(cos(i), s21_cos(i), EPS);

}
END_TEST

START_TEST(s21_cos_test_6)
{
#line 198
ck_assert_double_nan(s21_cos(-0.0/0.0));

}
END_TEST

START_TEST(s21_cos_test_7)
{
#line 201
for (double i = -10009.6; i <= -9808.0; i += 0.1)
    ck_assert_double_eq_tol(cos(i), s21_cos(i), EPS);

}
END_TEST

START_TEST(s21_cos_test_8)
{
#line 205
for (double i = 9809.6; i <= 10890.0; i += 0.1)
    ck_assert_double_eq_tol(cos(i), s21_cos(i), EPS);



//! s21_pow tests
}
END_TEST

START_TEST(s21_pow_test_1)
{
#line 212
ck_assert_double_eq_tol(pow(0.3123, 0.789456), s21_pow(0.3123, 0.789456), 1e-6);

}
END_TEST

START_TEST(s21_pow_test_2)
{
#line 215
ck_assert_double_eq_tol(pow(56.3, 0.3), s21_pow(56.3, 0.3), 1e-6);

}
END_TEST

START_TEST(s21_pow_test_3)
{
#line 218
ck_assert_double_eq(pow(1, 0), s21_pow(1, 0));

}
END_TEST

START_TEST(s21_pow_test_4)
{
#line 221
ck_assert_double_eq(pow(-1, 3), s21_pow(-1, 3));

}
END_TEST

START_TEST(s21_pow_test_5)
{
#line 224
ck_assert_double_eq(pow(-1, 4), s21_pow(-1, 4));

}
END_TEST

START_TEST(s21_pow_test_6)
{
#line 227
ck_assert_double_eq(pow(0, 0), s21_pow(0, 0));

}
END_TEST

START_TEST(s21_pow_test_7)
{
#line 230
ck_assert_double_eq(pow(0, -1), s21_pow(0, -1));

}
END_TEST

START_TEST(s21_pow_test_8)
{
#line 233
ck_assert_double_eq(pow(0, 1), s21_pow(0, 1));

}
END_TEST

START_TEST(s21_pow_test_9)
{
#line 236
ck_assert_double_eq(pow(INFINITY, 0), s21_pow(S21_HUGE_VAL, 0));

}
END_TEST

START_TEST(s21_pow_test_10)
{
#line 239
ck_assert_double_eq(pow(INFINITY, -1), s21_pow(S21_HUGE_VAL, -1));

}
END_TEST

START_TEST(s21_pow_test_13)
{
#line 242
ck_assert_double_nan(s21_pow(0, S21_NAN_VAL));

}
END_TEST

START_TEST(s21_pow_test_15)
{
#line 245
ck_assert_double_nan(s21_pow(S21_NAN_VAL, S21_NAN_VAL));

}
END_TEST

START_TEST(s21_pow_test_16)
{
#line 248
ck_assert_double_eq(pow(INFINITY, INFINITY), s21_pow(S21_HUGE_VAL, S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_pow_test_22)
{
#line 251
ck_assert_double_nan(s21_pow(S21_NAN_VAL, S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_pow_test_23)
{
#line 254
ck_assert_double_nan(s21_pow(S21_HUGE_VAL, S21_NAN_VAL));

}
END_TEST

START_TEST(s21_pow_test_24)
{
#line 257
ck_assert_double_nan(s21_pow(S21_NAN_VAL, -S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_pow_test_25)
{
#line 260
ck_assert_double_nan(s21_pow(-S21_HUGE_VAL, S21_NAN_VAL));

}
END_TEST

START_TEST(s21_pow_test_26)
{
#line 263
ck_assert_double_eq(pow(2, INFINITY), s21_pow(2, S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_pow_test_27)
{
#line 266
ck_assert_double_nan(s21_pow(-0.789456, -0.789456));

}
END_TEST

START_TEST(s21_pow_test_28)
{
#line 269
ck_assert_double_nan(s21_pow(-500.789456, -10.1354323));

}
END_TEST

START_TEST(s21_pow_test_29)
{
#line 272
ck_assert_double_nan(s21_pow(-500.789456, 34.13));

}
END_TEST

START_TEST(s21_pow_test_30)
{
#line 275
ck_assert_double_eq_tol(pow(10.789456, 3.13), s21_pow(10.789456, 3.13), 1e-2);

}
END_TEST

START_TEST(s21_pow_test_31)
{
#line 278
ck_assert_double_eq(pow(-1, -S21_HUGE_VAL), s21_pow(-1, -S21_HUGE_VAL));

//! s21_log tests

}
END_TEST

START_TEST(s21_log_test_1)
{
#line 283
for (double k = 1; k < 100; k += 13.2) {
    double a = s21_log(k);
    double b = log(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
}

}
END_TEST

START_TEST(s21_log_test_2)
{
#line 290
for (double k = 0.1; k < 4; k += 0.24) {
    double a = s21_log(k);
    double b = log(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
}

}
END_TEST

START_TEST(s21_log_test_3)
{
#line 297
for (double k = 0.1; k < 10000; k += 123) {
    double a = s21_log(k);
    double b = log(k);
    ck_assert_double_eq_tol(a, b, 1e-3);
}

}
END_TEST

START_TEST(s21_log_test_4)
{
#line 304
for (double k = 0.000005; k < 1; k *= 5) {
    double a = s21_log(k);
    double b = log(k);
    ck_assert_double_eq_tol(a, b, 1e-6);
}

}
END_TEST

START_TEST(s21_log_test_5)
{
#line 311
ck_assert_double_nan(s21_log(S21_NAN_VAL));

}
END_TEST

START_TEST(s21_log_test_6)
{
#line 314
ck_assert_double_eq(log(0), s21_log(0));

}
END_TEST

START_TEST(s21_log_test_7)
{
#line 317
ck_assert_double_nan(s21_log(-3));

}
END_TEST

START_TEST(s21_log_test_8)
{
#line 320
ck_assert_double_eq(log(INFINITY), s21_log(S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_log_test_9)
{
#line 323
ck_assert_double_nan(s21_log(-S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_log_test_10)
{
#line 326
ck_assert_double_eq(log(1), s21_log(1));

}
END_TEST

START_TEST(s21_log_test_11)
{
#line 329
ck_assert_double_eq_tol(log(2), s21_log(2), 1e-6);

}
END_TEST

START_TEST(s21_log_test_12)
{
#line 332
ck_assert_double_nan(s21_log(-S21_HUGE_VAL * 2));

}
END_TEST

START_TEST(s21_log_test_13)
{
#line 335
ck_assert_double_eq_tol(log(0.0001), s21_log(0.0001), 1e-6);

//! s21_floor tests

}
END_TEST

START_TEST(s21_floor_test_1)
{
#line 340
ck_assert_double_eq(floor(INFINITY), s21_floor(S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_floor_test_2)
{
#line 343
ck_assert_double_eq(floor(-INFINITY), s21_floor(-S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_floor_test_3)
{
#line 346
ck_assert_double_nan(floor(NAN));

}
END_TEST

START_TEST(s21_floor_test_4)
{
#line 349
ck_assert_double_nan(s21_floor(NAN));

}
END_TEST

START_TEST(s21_floor_test_5)
{
#line 352
ck_assert_int_eq(floor(-7.0), s21_floor(-7.0));

}
END_TEST

START_TEST(s21_floor_test_6)
{
#line 355
ck_assert_double_eq(floor(-98.1), s21_floor(-98.1));

}
END_TEST

START_TEST(s21_floor_test_7)
{
#line 358
ck_assert_double_eq(floor(123.02), s21_floor(123.02));

}
END_TEST

START_TEST(s21_floor_test_8)
{
#line 361
ck_assert_double_eq(floor(10009.00123), s21_floor(10009.00123));

}
END_TEST

START_TEST(s21_floor_test_9)
{
#line 364
ck_assert_double_eq(floor(-10009.555), s21_floor(-10009.555));

}
END_TEST

START_TEST(s21_floor_test_10)
{
#line 367
ck_assert_double_eq(floor(-0.10009), s21_floor(-0.10009));

}
END_TEST

START_TEST(s21_floor_test_11)
{
#line 370
ck_assert_double_eq(floor(-1e-23), s21_floor(-1e-23));

}
END_TEST

START_TEST(s21_floor_test_12)
{
#line 373
ck_assert_double_eq(floor(100091234.5), s21_floor(100091234.5));

}
END_TEST

START_TEST(s21_floor_test_13)
{
#line 376
ck_assert_double_eq(floor(7), s21_floor(7));

}
END_TEST

START_TEST(s21_floor_test_14)
{
#line 379
ck_assert_double_eq(floor(0), s21_floor(0));

}
END_TEST

START_TEST(s21_floor_test_15)
{
#line 382
ck_assert_double_eq(floor(0.0), s21_floor(0.0));

//! s21_exp tests

}
END_TEST

START_TEST(s21_exp_test_1)
{
#line 387
ck_assert_double_eq_tol(s21_exp(3.3333), s21_exp(3.3333), 1e-6);

}
END_TEST

START_TEST(s21_exp_test_2)
{
#line 390
ck_assert_double_eq_tol(s21_exp(-5.5), s21_exp(-5.5), 1e-6);

}
END_TEST

START_TEST(s21_exp_test_3)
{
#line 393
ck_assert_double_eq(s21_exp(4566.7899), s21_exp(4566.7899));

}
END_TEST

START_TEST(s21_exp_test_4)
{
#line 396
ck_assert_double_nan(s21_exp(NAN));

}
END_TEST

START_TEST(s21_exp_test_5)
{
#line 399
ck_assert_double_eq(exp(INFINITY), s21_exp(INFINITY));

}
END_TEST

START_TEST(s21_exp_test_6)
{
#line 402
ck_assert_double_eq_tol(exp(0.4564), s21_exp(0.4564), 1e-6);

}
END_TEST

START_TEST(s21_exp_test_7)
{
#line 405
ck_assert_double_eq(exp(0), s21_exp(0));

}
END_TEST

START_TEST(s21_exp_test_8)
{
#line 408
ck_assert_double_eq_tol(exp(1), s21_exp(1), 1e-6);

}
END_TEST

START_TEST(s21_exp_test_9)
{
#line 411
ck_assert_double_eq_tol(exp(-1), s21_exp(-1), 1e-6);

}
END_TEST

START_TEST(s21_exp_test_10)
{
#line 414
ck_assert_double_eq_tol(exp(-0.000001), s21_exp(-0.000001), 1e-6);

}
END_TEST

START_TEST(s21_exp_test_11)
{
#line 417
for (double i = -2.7863; i <= 2.6831; i += 0.001)
    ck_assert_double_eq_tol(exp(i), s21_exp(i), 1e-6);

//! s21_sin tests

}
END_TEST

START_TEST(s21_sin_test_1)
{
#line 423
for (double i = -1.000000; i <= 1.000000; i += 0.00001)
    ck_assert_double_eq_tol(sin(i), s21_sin(i), EPS);
        
}
END_TEST

START_TEST(s21_sin_test_2)
{
#line 427
ck_assert_double_nan(s21_sin(S21_NAN_VAL));

}
END_TEST

START_TEST(s21_sin_test_3)
{
#line 430
ck_assert_double_nan(s21_sin(S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_sin_test_4)
{
#line 433
ck_assert_double_nan(s21_sin(-S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_sin_test_5)
{
#line 436
for (double i = -223.654; i <= 148.522; i += 2.456)
    ck_assert_double_eq_tol(sin(i), s21_sin(i), EPS);

}
END_TEST

START_TEST(s21_sin_test_6)
{
#line 440
ck_assert_double_nan(s21_sin(-0.0/0.0));

}
END_TEST

START_TEST(s21_sin_test_7)
{
#line 443
for (double i = -10009.6; i <= -9808.0; i += 0.1)
    ck_assert_double_eq_tol(sin(i), s21_sin(i), EPS);

}
END_TEST

START_TEST(s21_sin_test_8)
{
#line 447
for (double i = 9809.6; i <= 10890.0; i += 0.1)
    ck_assert_double_eq_tol(sin(i), s21_sin(i), EPS);

//! s21_sqrt tests

}
END_TEST

START_TEST(s21_sqrt_test_1)
{
#line 453
ck_assert_double_eq_tol(s21_sqrt(233), sqrt(233), 1e-6);

}
END_TEST

START_TEST(s21_sqrt_test_2)
{
#line 456
ck_assert_double_nan(s21_sqrt(S21_NAN_VAL));

}
END_TEST

START_TEST(s21_sqrt_test_3)
{
#line 459
ck_assert_double_nan(sqrt(NAN));

}
END_TEST

START_TEST(s21_sqrt_test_4)
{
#line 462
ck_assert_double_eq(s21_sqrt(S21_HUGE_VAL), sqrt(INFINITY));

}
END_TEST

START_TEST(s21_sqrt_test_5)
{
#line 465
ck_assert_double_nan(s21_sqrt(-S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_sqrt_test_6)
{
#line 468
ck_assert_double_nan(sqrt(-INFINITY));

}
END_TEST

START_TEST(s21_sqrt_test_7)
{
#line 471
ck_assert_double_nan(s21_sqrt(-5));

}
END_TEST

START_TEST(s21_sqrt_test_8)
{
#line 474
ck_assert_double_nan(sqrt(-0.000001));

}
END_TEST

START_TEST(s21_sqrt_test_9)
{
#line 477
ck_assert_double_eq_tol(s21_sqrt(1000), sqrt(1000), 1e-7);

}
END_TEST

START_TEST(s21_sqrt_test_10)
{
#line 480
ck_assert_double_eq_tol(s21_sqrt(0.000001), sqrt(0.000001), 1e-7);

//! s21_tan tests

}
END_TEST

START_TEST(s21_tan_test_1)
{
#line 485
ck_assert_double_eq_tol(tan(0.123456), s21_tan(0.123456), 1e-6);

}
END_TEST

START_TEST(s21_tan_test_2)
{
#line 488
ck_assert_double_nan(s21_tan(S21_NAN_VAL));

}
END_TEST

START_TEST(s21_tan_test_3)
{
#line 491
ck_assert_double_nan(s21_tan(S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_tan_test_4)
{
#line 494
ck_assert_double_nan(s21_tan(-S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_tan_test_5)
{
#line 497
ck_assert_double_eq_tol(tan(-0.123456), s21_tan(-0.123456), 1e-6);

}
END_TEST

START_TEST(s21_tan_test_6)
{
#line 500
ck_assert_double_eq_tol(tan(11115.123456), s21_tan(11115.123456), 1e-6);

}
END_TEST

START_TEST(s21_tan_test_7)
{
#line 503
ck_assert_double_eq_tol(tan(-11115.123456), s21_tan(-11115.123456), 1e-6);

}
END_TEST

START_TEST(s21_tan_test_8)
{
#line 506
ck_assert_double_eq_tol(tan(0.000001), s21_tan(0.000001), 1e-6);

}
END_TEST

START_TEST(s21_tan_test_9)
{
#line 509
ck_assert_double_eq_tol(tan(-0.0), s21_tan(-0.0), 1e-6);

}
END_TEST

START_TEST(s21_tan_test_10)
{
#line 512
ck_assert_double_nan(s21_tan(-0.0/0.0));

//! s21_fabs tests

}
END_TEST

START_TEST(s21_fabs_test_1)
{
#line 517
ck_assert_double_eq(fabs(-INFINITY), s21_fabs(-S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_fabs_test_2)
{
#line 520
ck_assert_double_nan(fabs(NAN));

}
END_TEST

START_TEST(s21_fabs_test_3)
{
#line 523
ck_assert_double_nan(s21_fabs(S21_NAN_VAL));

}
END_TEST

START_TEST(s21_fabs_test_4)
{
#line 526
ck_assert_double_eq(fabs(-7.0), s21_fabs(-7.0));

}
END_TEST

START_TEST(s21_fabs_test_5)
{
#line 529
ck_assert_double_eq(fabs(-98.1), s21_fabs(-98.1));

}
END_TEST

START_TEST(s21_fabs_test_6)
{
#line 532
ck_assert_double_eq(fabs(123.02), s21_fabs(123.02));

}
END_TEST

START_TEST(s21_fabs_test_7)
{
#line 535
ck_assert_double_eq(fabs(10009.0), s21_fabs(10009.0));

}
END_TEST

START_TEST(s21_fabs_test_8)
{
#line 538
ck_assert_double_eq(fabs(-10009.555), s21_fabs(-10009.555));

}
END_TEST

START_TEST(s21_fabs_test_9)
{
#line 541
ck_assert_double_eq(fabs(-0.10009), s21_fabs(-0.10009));

}
END_TEST

START_TEST(s21_fabs_test_10)
{
#line 544
ck_assert_double_eq(fabs(-1e23), s21_fabs(-1e23));

}
END_TEST

START_TEST(s21_fabs_test_11)
{
#line 547
ck_assert_double_eq(fabs(INFINITY), s21_fabs(S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_fabs_test_12)
{
#line 550
ck_assert_double_eq(fabs(0.000213), s21_fabs(0.000213));

//! s21_fmod tests

}
END_TEST

START_TEST(s21_fmod_test_1)
{
#line 555
ck_assert_double_nan(fmod(1, 0));

}
END_TEST

START_TEST(s21_fmod_test_2)
{
#line 558
ck_assert_double_nan(s21_fmod(1, 0));

}
END_TEST

START_TEST(s21_fmod_test_3)
{
#line 561
ck_assert_double_eq(fmod(0, -1), s21_fmod(0, -1));

}
END_TEST

START_TEST(s21_fmod_test_4)
{
#line 564
ck_assert_double_eq(fmod(0, 1), s21_fmod(0, 1));

}
END_TEST

START_TEST(s21_fmod_test_5)
{
#line 567
ck_assert_double_nan(fmod(INFINITY, -1));

}
END_TEST

START_TEST(s21_fmod_test_6)
{
#line 570
ck_assert_double_nan(s21_fmod(INFINITY, -1));

}
END_TEST

START_TEST(s21_fmod_test_7)
{
#line 573
ck_assert_double_eq(fmod(-1, -INFINITY), s21_fmod(-1, -S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_fmod_test_8)
{
#line 576
ck_assert_double_eq(fmod(0, INFINITY), s21_fmod(0, S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_fmod_test_9)
{
#line 579
ck_assert_double_nan(s21_fmod(0, S21_NAN_VAL));

}
END_TEST

START_TEST(s21_fmod_test_10)
{
#line 582
ck_assert_double_nan(fmod(0, NAN));

}
END_TEST

START_TEST(s21_fmod_test_11)
{
#line 585
ck_assert_double_nan(s21_fmod(S21_NAN_VAL, S21_NAN_VAL));

}
END_TEST

START_TEST(s21_fmod_test_12)
{
#line 588
ck_assert_double_nan(fmod(NAN, NAN));

}
END_TEST

START_TEST(s21_fmod_test_13)
{
#line 591
ck_assert_double_nan(s21_fmod(S21_NAN_VAL, S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_fmod_test_14)
{
#line 594
ck_assert_double_nan(s21_fmod(S21_HUGE_VAL, S21_NAN_VAL));

}
END_TEST

START_TEST(s21_fmod_test_15)
{
#line 597
ck_assert_double_nan(s21_fmod(S21_NAN_VAL, -S21_HUGE_VAL));

}
END_TEST

START_TEST(s21_fmod_test_16)
{
#line 600
ck_assert_double_nan(s21_fmod(-S21_HUGE_VAL, S21_NAN_VAL));

}
END_TEST

START_TEST(s21_fmod_test_17)
{
#line 603
ck_assert_double_nan(fmod(NAN, INFINITY));

}
END_TEST

START_TEST(s21_fmod_test_18)
{
#line 606
ck_assert_double_nan(fmod(INFINITY, NAN));

}
END_TEST

START_TEST(s21_fmod_test_19)
{
#line 609
ck_assert_double_nan(fmod(NAN, -INFINITY));

}
END_TEST

START_TEST(s21_fmod_test_20)
{
#line 612
ck_assert_double_nan(fmod(-INFINITY, NAN));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_abs_test_1);
    tcase_add_test(tc1_1, s21_abs_test_2);
    tcase_add_test(tc1_1, s21_abs_test_3);
    tcase_add_test(tc1_1, s21_abs_test_4);
    tcase_add_test(tc1_1, s21_abs_test_5);
    tcase_add_test(tc1_1, s21_acos_test_1);
    tcase_add_test(tc1_1, s21_acos_test_2);
    tcase_add_test(tc1_1, s21_acos_test_3);
    tcase_add_test(tc1_1, s21_acos_test_4);
    tcase_add_test(tc1_1, s21_acos_test_5);
    tcase_add_test(tc1_1, s21_acos_test_6);
    tcase_add_test(tc1_1, s21_acos_test_7);
    tcase_add_test(tc1_1, s21_acos_test_8);
    tcase_add_test(tc1_1, s21_acos_test_9);
    tcase_add_test(tc1_1, s21_acos_test_10);
    tcase_add_test(tc1_1, s21_asin_test_1);
    tcase_add_test(tc1_1, s21_asin_test_2);
    tcase_add_test(tc1_1, s21_asin_test_3);
    tcase_add_test(tc1_1, s21_asin_test_4);
    tcase_add_test(tc1_1, s21_asin_test_5);
    tcase_add_test(tc1_1, s21_asin_test_6);
    tcase_add_test(tc1_1, s21_asin_test_7);
    tcase_add_test(tc1_1, s21_asin_test_8);
    tcase_add_test(tc1_1, s21_asin_test_9);
    tcase_add_test(tc1_1, s21_asin_test_10);
    tcase_add_test(tc1_1, s21_atan_test_1);
    tcase_add_test(tc1_1, s21_atan_test_2);
    tcase_add_test(tc1_1, s21_atan_test_3);
    tcase_add_test(tc1_1, s21_atan_test_4);
    tcase_add_test(tc1_1, s21_atan_test_5);
    tcase_add_test(tc1_1, s21_atan_test_6);
    tcase_add_test(tc1_1, s21_atan_test_7);
    tcase_add_test(tc1_1, s21_atan_test_8);
    tcase_add_test(tc1_1, s21_atan_test_9);
    tcase_add_test(tc1_1, s21_atan_test_10);
    tcase_add_test(tc1_1, s21_ceil_test_1);
    tcase_add_test(tc1_1, s21_ceil_test_2);
    tcase_add_test(tc1_1, s21_ceil_test_3);
    tcase_add_test(tc1_1, s21_ceil_test_4);
    tcase_add_test(tc1_1, s21_ceil_test_5);
    tcase_add_test(tc1_1, s21_ceil_test_6);
    tcase_add_test(tc1_1, s21_ceil_test_7);
    tcase_add_test(tc1_1, s21_ceil_test_8);
    tcase_add_test(tc1_1, s21_ceil_test_9);
    tcase_add_test(tc1_1, s21_ceil_test_10);
    tcase_add_test(tc1_1, s21_ceil_test_11);
    tcase_add_test(tc1_1, s21_ceil_test_12);
    tcase_add_test(tc1_1, s21_ceil_test_13);
    tcase_add_test(tc1_1, s21_ceil_test_14);
    tcase_add_test(tc1_1, s21_ceil_test_15);
    tcase_add_test(tc1_1, s21_cos_test_1);
    tcase_add_test(tc1_1, s21_cos_test_2);
    tcase_add_test(tc1_1, s21_cos_test_3);
    tcase_add_test(tc1_1, s21_cos_test_4);
    tcase_add_test(tc1_1, s21_cos_test_5);
    tcase_add_test(tc1_1, s21_cos_test_6);
    tcase_add_test(tc1_1, s21_cos_test_7);
    tcase_add_test(tc1_1, s21_cos_test_8);
    tcase_add_test(tc1_1, s21_pow_test_1);
    tcase_add_test(tc1_1, s21_pow_test_2);
    tcase_add_test(tc1_1, s21_pow_test_3);
    tcase_add_test(tc1_1, s21_pow_test_4);
    tcase_add_test(tc1_1, s21_pow_test_5);
    tcase_add_test(tc1_1, s21_pow_test_6);
    tcase_add_test(tc1_1, s21_pow_test_7);
    tcase_add_test(tc1_1, s21_pow_test_8);
    tcase_add_test(tc1_1, s21_pow_test_9);
    tcase_add_test(tc1_1, s21_pow_test_10);
    tcase_add_test(tc1_1, s21_pow_test_13);
    tcase_add_test(tc1_1, s21_pow_test_15);
    tcase_add_test(tc1_1, s21_pow_test_16);
    tcase_add_test(tc1_1, s21_pow_test_22);
    tcase_add_test(tc1_1, s21_pow_test_23);
    tcase_add_test(tc1_1, s21_pow_test_24);
    tcase_add_test(tc1_1, s21_pow_test_25);
    tcase_add_test(tc1_1, s21_pow_test_26);
    tcase_add_test(tc1_1, s21_pow_test_27);
    tcase_add_test(tc1_1, s21_pow_test_28);
    tcase_add_test(tc1_1, s21_pow_test_29);
    tcase_add_test(tc1_1, s21_pow_test_30);
    tcase_add_test(tc1_1, s21_pow_test_31);
    tcase_add_test(tc1_1, s21_log_test_1);
    tcase_add_test(tc1_1, s21_log_test_2);
    tcase_add_test(tc1_1, s21_log_test_3);
    tcase_add_test(tc1_1, s21_log_test_4);
    tcase_add_test(tc1_1, s21_log_test_5);
    tcase_add_test(tc1_1, s21_log_test_6);
    tcase_add_test(tc1_1, s21_log_test_7);
    tcase_add_test(tc1_1, s21_log_test_8);
    tcase_add_test(tc1_1, s21_log_test_9);
    tcase_add_test(tc1_1, s21_log_test_10);
    tcase_add_test(tc1_1, s21_log_test_11);
    tcase_add_test(tc1_1, s21_log_test_12);
    tcase_add_test(tc1_1, s21_log_test_13);
    tcase_add_test(tc1_1, s21_floor_test_1);
    tcase_add_test(tc1_1, s21_floor_test_2);
    tcase_add_test(tc1_1, s21_floor_test_3);
    tcase_add_test(tc1_1, s21_floor_test_4);
    tcase_add_test(tc1_1, s21_floor_test_5);
    tcase_add_test(tc1_1, s21_floor_test_6);
    tcase_add_test(tc1_1, s21_floor_test_7);
    tcase_add_test(tc1_1, s21_floor_test_8);
    tcase_add_test(tc1_1, s21_floor_test_9);
    tcase_add_test(tc1_1, s21_floor_test_10);
    tcase_add_test(tc1_1, s21_floor_test_11);
    tcase_add_test(tc1_1, s21_floor_test_12);
    tcase_add_test(tc1_1, s21_floor_test_13);
    tcase_add_test(tc1_1, s21_floor_test_14);
    tcase_add_test(tc1_1, s21_floor_test_15);
    tcase_add_test(tc1_1, s21_exp_test_1);
    tcase_add_test(tc1_1, s21_exp_test_2);
    tcase_add_test(tc1_1, s21_exp_test_3);
    tcase_add_test(tc1_1, s21_exp_test_4);
    tcase_add_test(tc1_1, s21_exp_test_5);
    tcase_add_test(tc1_1, s21_exp_test_6);
    tcase_add_test(tc1_1, s21_exp_test_7);
    tcase_add_test(tc1_1, s21_exp_test_8);
    tcase_add_test(tc1_1, s21_exp_test_9);
    tcase_add_test(tc1_1, s21_exp_test_10);
    tcase_add_test(tc1_1, s21_exp_test_11);
    tcase_add_test(tc1_1, s21_sin_test_1);
    tcase_add_test(tc1_1, s21_sin_test_2);
    tcase_add_test(tc1_1, s21_sin_test_3);
    tcase_add_test(tc1_1, s21_sin_test_4);
    tcase_add_test(tc1_1, s21_sin_test_5);
    tcase_add_test(tc1_1, s21_sin_test_6);
    tcase_add_test(tc1_1, s21_sin_test_7);
    tcase_add_test(tc1_1, s21_sin_test_8);
    tcase_add_test(tc1_1, s21_sqrt_test_1);
    tcase_add_test(tc1_1, s21_sqrt_test_2);
    tcase_add_test(tc1_1, s21_sqrt_test_3);
    tcase_add_test(tc1_1, s21_sqrt_test_4);
    tcase_add_test(tc1_1, s21_sqrt_test_5);
    tcase_add_test(tc1_1, s21_sqrt_test_6);
    tcase_add_test(tc1_1, s21_sqrt_test_7);
    tcase_add_test(tc1_1, s21_sqrt_test_8);
    tcase_add_test(tc1_1, s21_sqrt_test_9);
    tcase_add_test(tc1_1, s21_sqrt_test_10);
    tcase_add_test(tc1_1, s21_tan_test_1);
    tcase_add_test(tc1_1, s21_tan_test_2);
    tcase_add_test(tc1_1, s21_tan_test_3);
    tcase_add_test(tc1_1, s21_tan_test_4);
    tcase_add_test(tc1_1, s21_tan_test_5);
    tcase_add_test(tc1_1, s21_tan_test_6);
    tcase_add_test(tc1_1, s21_tan_test_7);
    tcase_add_test(tc1_1, s21_tan_test_8);
    tcase_add_test(tc1_1, s21_tan_test_9);
    tcase_add_test(tc1_1, s21_tan_test_10);
    tcase_add_test(tc1_1, s21_fabs_test_1);
    tcase_add_test(tc1_1, s21_fabs_test_2);
    tcase_add_test(tc1_1, s21_fabs_test_3);
    tcase_add_test(tc1_1, s21_fabs_test_4);
    tcase_add_test(tc1_1, s21_fabs_test_5);
    tcase_add_test(tc1_1, s21_fabs_test_6);
    tcase_add_test(tc1_1, s21_fabs_test_7);
    tcase_add_test(tc1_1, s21_fabs_test_8);
    tcase_add_test(tc1_1, s21_fabs_test_9);
    tcase_add_test(tc1_1, s21_fabs_test_10);
    tcase_add_test(tc1_1, s21_fabs_test_11);
    tcase_add_test(tc1_1, s21_fabs_test_12);
    tcase_add_test(tc1_1, s21_fmod_test_1);
    tcase_add_test(tc1_1, s21_fmod_test_2);
    tcase_add_test(tc1_1, s21_fmod_test_3);
    tcase_add_test(tc1_1, s21_fmod_test_4);
    tcase_add_test(tc1_1, s21_fmod_test_5);
    tcase_add_test(tc1_1, s21_fmod_test_6);
    tcase_add_test(tc1_1, s21_fmod_test_7);
    tcase_add_test(tc1_1, s21_fmod_test_8);
    tcase_add_test(tc1_1, s21_fmod_test_9);
    tcase_add_test(tc1_1, s21_fmod_test_10);
    tcase_add_test(tc1_1, s21_fmod_test_11);
    tcase_add_test(tc1_1, s21_fmod_test_12);
    tcase_add_test(tc1_1, s21_fmod_test_13);
    tcase_add_test(tc1_1, s21_fmod_test_14);
    tcase_add_test(tc1_1, s21_fmod_test_15);
    tcase_add_test(tc1_1, s21_fmod_test_16);
    tcase_add_test(tc1_1, s21_fmod_test_17);
    tcase_add_test(tc1_1, s21_fmod_test_18);
    tcase_add_test(tc1_1, s21_fmod_test_19);
    tcase_add_test(tc1_1, s21_fmod_test_20);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
